const WATERFALLS=[['Yosemite Falls',-560,-260,739],['Bridalveil Fall',480,310,188],['Vernal Fall',850,-620,97],['Nevada Fall',1050,-820,181],['Ribbon Fall',-770,80,491],['Horsetail Fall',105,740,480]];
const TIMES={dawn:['#ffb36a','#26345f'],noon:['#dff6ff','#78b8ff'],golden:['#ffd28a','#345b92'],dusk:['#7655ff','#1a1738'],night:['#8fb8ff','#020713']};
const state={x:0,y:150,z:620,vx:0,vy:0,vz:-82,pitch:0,roll:0,yaw:Math.PI,throttle:.72,gear:true,brake:false,weather:'calm',time:'dawn',attempts:0,crashes:[],trees:[],aurora:true};
for(let i=0;i<5200;i++){let x=(Math.random()-.5)*2200,z=(Math.random()-.5)*1600,y=heightAt(x,z);if(y>25&&!(Math.abs(x)<100&&Math.abs(z)<720))state.trees.push([x,y,z,.5+Math.random()*1.6]);}
document.getElementById('open').onclick=()=>start();
function start(){document.body.innerHTML='<canvas id="c"></canvas><div class="hud glass"><b>B737 MAX 9</b><span id="speed"></span><span id="alt"></span><span id="wind"></span><span id="gear"></span><span id="tries"></span><span id="tod"></span><small>W/S throttle • ↑↓ pitch • ←→ roll • A/D yaw • G gear • B brakes • 1-5 time • H hurricane • N aurora • R respawn</small></div>';const c=document.getElementById('c'),ctx=c.getContext('2d');addEventListener('resize',()=>{c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)});dispatchEvent(new Event('resize'));loop(ctx)}
const keys={};onkeydown=e=>{keys[e.key.toLowerCase()]=true;if('12345'.includes(e.key))state.time=Object.keys(TIMES)[+e.key-1];if(e.key.toLowerCase()==='g')state.gear=!state.gear;if(e.key.toLowerCase()==='h')state.weather=state.weather==='hurricane'?'calm':'hurricane';if(e.key.toLowerCase()==='n')state.aurora=!state.aurora;if(e.key.toLowerCase()==='r')respawn()};onkeyup=e=>keys[e.key.toLowerCase()]=false;
function heightAt(x,z){return 18+170*Math.exp(-((Math.abs(x)-760)**2)/180000)+120*Math.exp(-(z*z)/850000)+28*Math.sin(x/130)*Math.cos(z/170)}
function physics(dt){state.throttle=Math.max(0,Math.min(1,state.throttle+(keys.w?dt*.3:0)-(keys.s?dt*.3:0)));state.pitch+=(keys.arrowup?1:keys.arrowdown?-1:0)*dt*.55;state.roll+=(keys.arrowleft?1:keys.arrowright?-1:0)*dt*.8;state.yaw+=(keys.a?1:keys.d?-1:0)*dt*.45;state.brake=!!keys.b;let speed=Math.hypot(state.vx,state.vy,state.vz),wind=state.weather==='hurricane'?45:5;state.vx+=Math.sin(state.yaw)*70*state.throttle*dt+Math.sin(performance.now()/700)*wind*.02*dt;state.vz+=Math.cos(state.yaw)*70*state.throttle*dt+wind*.01*dt;let lift=Math.max(0,(speed-42)*.018)*(state.gear?.82:1),drag=.006*speed*(state.gear?1.8:1)+(state.brake?.05:0);state.vx-=state.vx*drag*dt;state.vz-=state.vz*drag*dt;state.vy+=(lift-9.81)*dt;state.x+=state.vx*dt;state.y+=state.vy*dt;state.z+=state.vz*dt;let ground=heightAt(state.x,state.z)+7;if(state.y<ground){let hard=Math.abs(state.vy)>5||speed>95||Math.abs(state.roll)>0.55;state.y=ground;if(hard){state.crashes.push([state.x,state.z,performance.now()]);respawn()}else{state.vx*=.55;state.vz*=.55;state.vy=0}}}
function respawn(){state.x=0;state.y=150;state.z=620;state.vx=0;state.vy=0;state.vz=-85;state.pitch=0;state.roll=0;state.yaw=Math.PI;state.attempts++}
function project(x,y,z){let dx=x-state.x,dy=y-state.y,dz=z-state.z,cy=Math.cos(-state.yaw),sy=Math.sin(-state.yaw),rx=dx*cy-dz*sy,rz=dx*sy+dz*cy+260,scale=650/Math.max(20,rz);return [innerWidth/2+rx*scale,innerHeight*.55-dy*scale,scale,rz]}
function loop(ctx){let last=performance.now();function frame(now){let dt=Math.min(.033,(now-last)/1000);last=now;physics(dt);draw(ctx,now);requestAnimationFrame(frame)}requestAnimationFrame(frame)}
function draw(ctx,t){let [top,bot]=TIMES[state.time];let g=ctx.createLinearGradient(0,0,0,innerHeight);g.addColorStop(0,bot);g.addColorStop(1,top);ctx.fillStyle=g;ctx.fillRect(0,0,innerWidth,innerHeight);if(state.aurora){ctx.globalAlpha=.35;for(let i=0;i<5;i++){ctx.fillStyle=i%2?'#42ffba':'#8d5cff';ctx.beginPath();ctx.ellipse(innerWidth*(.2+i*.16),120+Math.sin(t/700+i)*35,260,28,Math.sin(i),0,7);ctx.fill()}ctx.globalAlpha=1}drawTerrain(ctx);drawObjects(ctx,t);drawPlane(ctx);hud()}
function drawTerrain(ctx){ctx.fillStyle='#314024';ctx.beginPath();ctx.moveTo(0,innerHeight);for(let sx=0;sx<=innerWidth;sx+=18){let wx=(sx-innerWidth/2)*2+state.x,wz=state.z-360,h=heightAt(wx,wz)-state.y;ctx.lineTo(sx,innerHeight*.62-h*2)}ctx.lineTo(innerWidth,innerHeight);ctx.fill();ctx.fillStyle='#46cfff99';ctx.fillRect(innerWidth/2-28,innerHeight*.62,56,innerHeight*.38)}
function drawObjects(ctx,t){let objs=[];for(const tr of state.trees){let p=project(...tr.slice(0,3));if(p[3]>20&&p[3]<2200)objs.push([p,tr])}objs.sort((a,b)=>b[0][3]-a[0][3]).slice(-900).forEach(([p,tr])=>{ctx.fillStyle='#1e5f35';ctx.beginPath();ctx.moveTo(p[0],p[1]-18*tr[3]*p[2]);ctx.lineTo(p[0]-7*tr[3]*p[2],p[1]);ctx.lineTo(p[0]+7*tr[3]*p[2],p[1]);ctx.fill()});WATERFALLS.forEach(w=>{let p=project(w[1],heightAt(w[1],w[2])+w[3]/3,w[2]);if(p[3]>0){ctx.strokeStyle='#dff8ffcc';ctx.lineWidth=Math.max(2,24*p[2]);ctx.beginPath();ctx.moveTo(p[0],p[1]);ctx.lineTo(p[0],p[1]+w[3]*p[2]/3);ctx.stroke();ctx.fillStyle='white';ctx.fillText(w[0],p[0]+12,p[1])}});state.crashes.forEach(c=>{let p=project(c[0],heightAt(c[0],c[1])+8,c[1]);ctx.fillStyle='#ff4b00bb';ctx.beginPath();ctx.arc(p[0],p[1],Math.max(5,18*p[2]),0,7);ctx.fill()})}
function drawPlane(ctx){ctx.save();ctx.translate(innerWidth/2,innerHeight*.58);ctx.rotate(-state.roll);ctx.strokeStyle='#eaf5ff';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(0,-35);ctx.lineTo(0,35);ctx.moveTo(-58,0);ctx.lineTo(58,0);ctx.moveTo(-18,28);ctx.lineTo(18,28);ctx.stroke();ctx.restore()}
function hud(){let sp=Math.hypot(state.vx,state.vy,state.vz).toFixed(0),alt=Math.max(0,state.y-heightAt(state.x,state.z)).toFixed(0);speed.textContent='Speed '+sp+' m/s';alt.textContent='Alt '+alt+' m';wind.textContent='Wind '+state.weather;gear.textContent='Gear '+(state.gear?'DOWN':'UP');tries.textContent='Attempts '+state.attempts;tod.textContent='Time '+state.time}
